### ISSUE TITLE
Path Problem

### ISSUE THREAD

**Issue by Hawk768** [Xavy-13/qbittorrent#1]
I have set path to my TeamDrive but it still don't download directly there it takes my colab disk space how can I fix this

**Comment by Xavy-13** [comment]
Did you make sure that you put the TeamDrive path before running the 2nd cell ?
And because of colab backend, it will take some disk space before the files are written to google drive. So you should use this colab only with the torrent that's smaller than 60GB size

**Comment by Hawk768** [comment]
Thanks for the quick reply,yes I did put my TeamDrive path but even after
completing the download it's present in my drive but it still takes my
Colab Disk space

**Comment by Xavy-13** [comment]
Well i would say that's the problem of mounting system in colab itself, that's why i suggested not terminating the colab after torrenting. And if you want to download something else, I think the best way is to make a new colab and run it. You can do that by clicking "File" and then "Save a copy in Drive"

**Comment by Hawk768** [comment]
Gonna do that and I don't terminate Qbit right after my torrent downloads I
want to seed even if it's for half an hour but it doesn't seed,even after I
out it in super seed mode maybe peers don't connect that's why it happens.

**Comment by Xavy-13** [comment]
well if you want to seed a torrent, you should leave it for 10 days at least, which is impossible for colab. That means if you use this colab, you'll technically become a "leecher". You can only seed for anyone who's downloading at the same time like you

**Comment by Hawk768** [comment]
Can I seed if files are already present in my drive?

**Comment by Xavy-13** [comment]
Maybe you can by using the Torrent creator feature of qbittorrent. Make a torrent with your files in google drive and add some trackers. But I haven't tried this method before

**Comment by Hawk768** [comment]
Wouldn't just make another torrent,well whatever I don't think I want to
use Google Collab as seedbox.

Thanks for the all replies, suggestion and clearing my doubts

**Comment by Xavy-13** [comment]
Enjoy
